import AbstractGraphicComponent from "../../AbstractGraphicComponent.js";
import CollectionCardGraphicComponent from "../../Card/CollectionCardGraphicComponent.js";
class CardPreviewGraphicComponent extends AbstractGraphicComponent {
    constructor(container, card) {
        super(container);
        this._card = card;
        this._instanceContainer.style.width = "80%";
        this._instanceContainer.style.backgroundColor = "red";
        this._instanceContainer.style.display = "inline-block";
        this._instanceContainer.style.textAlign = "center";
        this._instanceContainer.style.padding = "20px";
        this._instanceContainer.style.borderRadius = "3px";
        let instanceTitlePreview = this.getCurrentDocument().createElement('div');
        instanceTitlePreview.innerHTML = "Character sheet";
        instanceTitlePreview.style.fontSize = "20px";
        instanceTitlePreview.style.textAlign = "left";
        instanceTitlePreview.style.marginBottom = "20px";
        instanceTitlePreview.style.fontWeight = "bold";
        let instanceContainerMainData = this.getCurrentDocument().createElement('div');
        instanceContainerMainData.style.width = "45%";
        instanceContainerMainData.style.display = "inline-block";
        instanceContainerMainData.style.verticalAlign = "top";
        let instanceContainerCenter = this.getCurrentDocument().createElement('div');
        instanceContainerCenter.style.width = "10%";
        instanceContainerCenter.style.display = "inline-block";
        instanceContainerCenter.style.verticalAlign = "top";
        let instanceContainerSecondaryData = this.getCurrentDocument().createElement('div');
        instanceContainerSecondaryData.style.width = "45%";
        instanceContainerSecondaryData.style.display = "inline-block";
        instanceContainerSecondaryData.style.verticalAlign = "top";
        let instanceTitleCapacities = this.getCurrentDocument().createElement('div');
        instanceTitleCapacities.innerHTML = "Capacities";
        instanceTitleCapacities.style.fontSize = "16px";
        instanceTitleCapacities.style.textAlign = "left";
        instanceTitleCapacities.style.marginBottom = "20px";
        instanceTitleCapacities.style.fontWeight = "bold";
        let instanceContainerCapacities = this.getCurrentDocument().createElement('div');
        instanceContainerCapacities.style.textAlign = "left";
        instanceContainerCapacities.style.marginBottom = "40px";
        let instanceTitleItems = this.getCurrentDocument().createElement('div');
        instanceTitleItems.innerHTML = "Items";
        instanceTitleItems.style.fontSize = "16px";
        instanceTitleItems.style.textAlign = "left";
        instanceTitleItems.style.marginBottom = "20px";
        instanceTitleItems.style.fontWeight = "bold";
        let instanceContainerItems = this.getCurrentDocument().createElement('div');
        instanceContainerItems.style.marginBottom = "40px";
        this._instanceContainer.appendChild(instanceTitlePreview);
        this._instanceContainer.appendChild(instanceContainerMainData);
        this._instanceContainer.appendChild(instanceContainerCenter);
        this._instanceContainer.appendChild(instanceContainerSecondaryData);
        this._instanceContainer.appendChild(instanceTitleCapacities);
        this._instanceContainer.appendChild(instanceContainerCapacities);
        this._instanceContainer.appendChild(instanceTitleItems);
        this._instanceContainer.appendChild(instanceContainerItems);
        let instanceCardontainer = this.getCurrentDocument().createElement('div');
        instanceCardontainer.style.display = "inline-block";
        instanceCardontainer.style.marginTop = "50px";
        const graphicCard = new CollectionCardGraphicComponent(this._container, this._card);
        instanceCardontainer.appendChild(graphicCard);
        instanceContainerMainData.appendChild(instanceCardontainer);
        let instanceHackCardInMiddle = this.getCurrentDocument().createElement('div');
        instanceHackCardInMiddle.style.height = "50px";
        instanceHackCardInMiddle.style.width = "100%";
        instanceContainerMainData.appendChild(instanceHackCardInMiddle);
        let templateMainCaracContainer = this.getCurrentDocument().createElement('div');
        templateMainCaracContainer.style.width = "100%";
        templateMainCaracContainer.style.display = "inline-block";
        templateMainCaracContainer.style.marginBottom = "5px";
        let templateMainCaracText = this.getCurrentDocument().createElement('div');
        templateMainCaracText.style.display = "inline-block";
        templateMainCaracText.style.width = "70%";
        templateMainCaracText.style.textAlign = "left";
        templateMainCaracText.style.color = "#3700b3";
        let templateMainCaracValue = this.getCurrentDocument().createElement('div');
        templateMainCaracValue.style.display = "inline-block";
        templateMainCaracValue.style.width = "30%";
        templateMainCaracValue.style.textAlign = "right";
        let templateSecondaryCaracContainer = this.getCurrentDocument().createElement('div');
        templateSecondaryCaracContainer.style.width = "100%";
        templateSecondaryCaracContainer.style.display = "inline-block";
        templateSecondaryCaracContainer.style.marginBottom = "5px";
        let templateSecondaryCaracText = this.getCurrentDocument().createElement('div');
        templateSecondaryCaracText.style.display = "inline-block";
        templateSecondaryCaracText.style.width = "70%";
        templateSecondaryCaracText.style.textAlign = "left";
        templateSecondaryCaracText.style.color = "#3700b3";
        let templateSecondaryCaracValue = this.getCurrentDocument().createElement('div');
        templateSecondaryCaracValue.style.display = "inline-block";
        templateSecondaryCaracValue.style.width = "30%";
        templateSecondaryCaracValue.style.textAlign = "right";
        let templateBlockSeperateSecondaryData = this.getCurrentDocument().createElement('div');
        templateBlockSeperateSecondaryData.style.height = "10px";
        // Strength
        let instanceMainCaracContainerStrength = templateMainCaracContainer.cloneNode(true);
        let instanceMainCaracTextStrength = templateMainCaracText.cloneNode(true);
        instanceMainCaracTextStrength.innerHTML = "Strength";
        let instanceMainCaracValueStrength = templateMainCaracValue.cloneNode(true);
        instanceMainCaracValueStrength.innerHTML = this._card.getStrength();
        instanceMainCaracContainerStrength.appendChild(instanceMainCaracTextStrength);
        instanceMainCaracContainerStrength.appendChild(instanceMainCaracValueStrength);
        instanceContainerMainData.appendChild(instanceMainCaracContainerStrength);
        // Dexterity
        let instanceMainCaracContainerDexterity = templateMainCaracContainer.cloneNode(true);
        let instanceMainCaracTextDexterity = templateMainCaracText.cloneNode(true);
        instanceMainCaracTextDexterity.innerHTML = "Dexterity";
        let instanceMainCaracValueDexterity = templateMainCaracValue.cloneNode(true);
        instanceMainCaracValueDexterity.innerHTML = this._card.getDexterity();
        instanceMainCaracContainerDexterity.appendChild(instanceMainCaracTextDexterity);
        instanceMainCaracContainerDexterity.appendChild(instanceMainCaracValueDexterity);
        instanceContainerMainData.appendChild(instanceMainCaracContainerDexterity);
        // Intelligence
        let instanceMainCaracContainerIntelligence = templateMainCaracContainer.cloneNode(true);
        let instanceMainCaracTextIntelligence = templateMainCaracText.cloneNode(true);
        instanceMainCaracTextIntelligence.innerHTML = "Intelligence";
        let instanceMainCaracValueIntelligence = templateMainCaracValue.cloneNode(true);
        instanceMainCaracValueIntelligence.innerHTML = this._card.getIntelligence();
        instanceMainCaracContainerIntelligence.appendChild(instanceMainCaracTextIntelligence);
        instanceMainCaracContainerIntelligence.appendChild(instanceMainCaracValueIntelligence);
        instanceContainerMainData.appendChild(instanceMainCaracContainerIntelligence);
        // Luck
        let instanceMainCaracContainerLuck = templateMainCaracContainer.cloneNode(true);
        let instanceMainCaracTextLuck = templateMainCaracText.cloneNode(true);
        instanceMainCaracTextLuck.innerHTML = "Luck";
        let instanceMainCaracValueLuck = templateMainCaracValue.cloneNode(true);
        instanceMainCaracValueLuck.innerHTML = this._card.getLuck();
        instanceMainCaracContainerLuck.appendChild(instanceMainCaracTextLuck);
        instanceMainCaracContainerLuck.appendChild(instanceMainCaracValueLuck);
        instanceContainerMainData.appendChild(instanceMainCaracContainerLuck);
        // PhysicalDamage
        let instanceSecondaryCaracContainerPhysicalDamage = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextPhysicalDamage = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextPhysicalDamage.innerHTML = "PhysicalDamage";
        let instanceSecondaryCaracValuePhysicalDamage = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValuePhysicalDamage.innerHTML = this._card.getPhysicalDamage();
        instanceSecondaryCaracContainerPhysicalDamage.appendChild(instanceSecondaryCaracTextPhysicalDamage);
        instanceSecondaryCaracContainerPhysicalDamage.appendChild(instanceSecondaryCaracValuePhysicalDamage);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerPhysicalDamage);
        // PhysicalCriticalRate
        let instanceSecondaryCaracContainerPhysicalCriticalRate = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextPhysicalCriticalRate = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextPhysicalCriticalRate.innerHTML = "PhysicalCriticalRate";
        let instanceSecondaryCaracValuePhysicalCriticalRate = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValuePhysicalCriticalRate.innerHTML = this._card.getPhysicalCriticalRate();
        instanceSecondaryCaracContainerPhysicalCriticalRate.appendChild(instanceSecondaryCaracTextPhysicalCriticalRate);
        instanceSecondaryCaracContainerPhysicalCriticalRate.appendChild(instanceSecondaryCaracValuePhysicalCriticalRate);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerPhysicalCriticalRate);
        // PhysicalCriticalNumber
        let instanceSecondaryCaracContainerPhysicalCriticalNumber = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextPhysicalCriticalNumber = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextPhysicalCriticalNumber.innerHTML = "PhysicalCriticalNumber";
        let instanceSecondaryCaracValuePhysicalCriticalNumber = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValuePhysicalCriticalNumber.innerHTML = this._card.getPhysicalCriticalNumber();
        instanceSecondaryCaracContainerPhysicalCriticalNumber.appendChild(instanceSecondaryCaracTextPhysicalCriticalNumber);
        instanceSecondaryCaracContainerPhysicalCriticalNumber.appendChild(instanceSecondaryCaracValuePhysicalCriticalNumber);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerPhysicalCriticalNumber);
        let instanceBlockSeperateSecondaryData1 = templateBlockSeperateSecondaryData.cloneNode(true);
        instanceContainerSecondaryData.appendChild(instanceBlockSeperateSecondaryData1);
        // MagicDamage
        let instanceSecondaryCaracContainerMagicDamage = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextMagicDamage = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextMagicDamage.innerHTML = "MagicDamage";
        let instanceSecondaryCaracValueMagicDamage = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueMagicDamage.innerHTML = this._card.getMagicDamage();
        instanceSecondaryCaracContainerMagicDamage.appendChild(instanceSecondaryCaracTextMagicDamage);
        instanceSecondaryCaracContainerMagicDamage.appendChild(instanceSecondaryCaracValueMagicDamage);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerMagicDamage);
        // MagicCriticalRate
        let instanceSecondaryCaracContainerMagicCriticalRate = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextMagicCriticalRate = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextMagicCriticalRate.innerHTML = "MagicCriticalRate";
        let instanceSecondaryCaracValueMagicCriticalRate = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueMagicCriticalRate.innerHTML = this._card.getMagicCriticalRate();
        instanceSecondaryCaracContainerMagicCriticalRate.appendChild(instanceSecondaryCaracTextMagicCriticalRate);
        instanceSecondaryCaracContainerMagicCriticalRate.appendChild(instanceSecondaryCaracValueMagicCriticalRate);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerMagicCriticalRate);
        // MagicCriticalNumber
        let instanceSecondaryCaracContainerMagicCriticalNumber = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextMagicCriticalNumber = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextMagicCriticalNumber.innerHTML = "MagicCriticalNumber";
        let instanceSecondaryCaracValueMagicCriticalNumber = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueMagicCriticalNumber.innerHTML = this._card.getMagicCriticalNumber();
        instanceSecondaryCaracContainerMagicCriticalNumber.appendChild(instanceSecondaryCaracTextMagicCriticalNumber);
        instanceSecondaryCaracContainerMagicCriticalNumber.appendChild(instanceSecondaryCaracValueMagicCriticalNumber);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerMagicCriticalNumber);
        let instanceBlockSeperateSecondaryData2 = templateBlockSeperateSecondaryData.cloneNode(true);
        instanceContainerSecondaryData.appendChild(instanceBlockSeperateSecondaryData2);
        // FireResistance
        let instanceSecondaryCaracContainerFireResistance = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextFireResistance = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextFireResistance.innerHTML = "FireResistance";
        let instanceSecondaryCaracValueFireResistance = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueFireResistance.innerHTML = this._card.getFireResistance();
        instanceSecondaryCaracContainerFireResistance.appendChild(instanceSecondaryCaracTextFireResistance);
        instanceSecondaryCaracContainerFireResistance.appendChild(instanceSecondaryCaracValueFireResistance);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerFireResistance);
        // WaterResistance
        let instanceSecondaryCaracContainerWaterResistance = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextWaterResistance = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextWaterResistance.innerHTML = "WaterResistance";
        let instanceSecondaryCaracValueWaterResistance = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueWaterResistance.innerHTML = this._card.getWaterResistance();
        instanceSecondaryCaracContainerWaterResistance.appendChild(instanceSecondaryCaracTextWaterResistance);
        instanceSecondaryCaracContainerWaterResistance.appendChild(instanceSecondaryCaracValueWaterResistance);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerWaterResistance);
        // PlantResistance
        let instanceSecondaryCaracContainerPlantResistance = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextPlantResistance = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextPlantResistance.innerHTML = "PlantResistance";
        let instanceSecondaryCaracValuePlantResistance = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValuePlantResistance.innerHTML = this._card.getPlantResistance();
        instanceSecondaryCaracContainerPlantResistance.appendChild(instanceSecondaryCaracTextPlantResistance);
        instanceSecondaryCaracContainerPlantResistance.appendChild(instanceSecondaryCaracValuePlantResistance);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerPlantResistance);
        // NecromancyResistance
        let instanceSecondaryCaracContainerNecromancyResistance = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextNecromancyResistance = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextNecromancyResistance.innerHTML = "NecromancyResistance";
        let instanceSecondaryCaracValueNecromancyResistance = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueNecromancyResistance.innerHTML = this._card.getNecromancyResistance();
        instanceSecondaryCaracContainerNecromancyResistance.appendChild(instanceSecondaryCaracTextNecromancyResistance);
        instanceSecondaryCaracContainerNecromancyResistance.appendChild(instanceSecondaryCaracValueNecromancyResistance);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerNecromancyResistance);
        // BlessingResistance
        let instanceSecondaryCaracContainerBlessingResistance = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextBlessingResistance = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextBlessingResistance.innerHTML = "BlessingResistance";
        let instanceSecondaryCaracValueBlessingResistance = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueBlessingResistance.innerHTML = this._card.getBlessingResistance();
        instanceSecondaryCaracContainerBlessingResistance.appendChild(instanceSecondaryCaracTextBlessingResistance);
        instanceSecondaryCaracContainerBlessingResistance.appendChild(instanceSecondaryCaracValueBlessingResistance);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerBlessingResistance);
        // Armor
        let instanceSecondaryCaracContainerArmor = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextArmor = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextArmor.innerHTML = "Armor";
        let instanceSecondaryCaracValueArmor = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueArmor.innerHTML = this._card.getArmor();
        instanceSecondaryCaracContainerArmor.appendChild(instanceSecondaryCaracTextArmor);
        instanceSecondaryCaracContainerArmor.appendChild(instanceSecondaryCaracValueArmor);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerArmor);
        1;
        let instanceBlockSeperateSecondaryData3 = templateBlockSeperateSecondaryData.cloneNode(true);
        instanceContainerSecondaryData.appendChild(instanceBlockSeperateSecondaryData3);
        // Accuracy
        let instanceSecondaryCaracContainerAccuracy = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextAccuracy = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextAccuracy.innerHTML = "Accuracy";
        let instanceSecondaryCaracValueAccuracy = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueAccuracy.innerHTML = this._card.getAccuracy();
        instanceSecondaryCaracContainerAccuracy.appendChild(instanceSecondaryCaracTextAccuracy);
        instanceSecondaryCaracContainerAccuracy.appendChild(instanceSecondaryCaracValueAccuracy);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerAccuracy);
        // Escape
        let instanceSecondaryCaracContainerEscape = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextEscape = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextEscape.innerHTML = "Escape";
        let instanceSecondaryCaracValueEscape = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueEscape.innerHTML = this._card.getEscape();
        instanceSecondaryCaracContainerEscape.appendChild(instanceSecondaryCaracTextEscape);
        instanceSecondaryCaracContainerEscape.appendChild(instanceSecondaryCaracValueEscape);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerEscape);
        let instanceBlockSeperateSecondaryData4 = templateBlockSeperateSecondaryData.cloneNode(true);
        instanceContainerSecondaryData.appendChild(instanceBlockSeperateSecondaryData4);
        // Life
        let instanceSecondaryCaracContainerLife = templateSecondaryCaracContainer.cloneNode(true);
        let instanceSecondaryCaracTextLife = templateSecondaryCaracText.cloneNode(true);
        instanceSecondaryCaracTextLife.innerHTML = "Life";
        let instanceSecondaryCaracValueLife = templateSecondaryCaracValue.cloneNode(true);
        instanceSecondaryCaracValueLife.innerHTML = this._card.getLife();
        instanceSecondaryCaracContainerLife.appendChild(instanceSecondaryCaracTextLife);
        instanceSecondaryCaracContainerLife.appendChild(instanceSecondaryCaracValueLife);
        instanceContainerSecondaryData.appendChild(instanceSecondaryCaracContainerLife);
        this._card.getCapacities().forEach((capacity) => {
            let capacityContainer = this.getCurrentDocument().createElement('div');
            capacityContainer.appendChild(capacity.getGraphic());
            instanceContainerCapacities.appendChild(capacityContainer);
        });
    }
}
customElements.define('card-preview', CardPreviewGraphicComponent);
export default CardPreviewGraphicComponent;
//# sourceMappingURL=CardPreviewGraphicComponent.js.map